In [ ]:
import torch 
x=torch.empty(3,2)
print(x)
x.shape

In [ ]:
x_rand=torch.rand(2,3)
print(x_rand)
print(x_rand.dtype)

In [ ]:
x_dt=torch.ones(2,2,dtype=torch.float16)
print(x_dt.dtype)

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x+y)

In [ ]:
y.add_(x)## _ means in place operation

In [ ]:
torch.subtract(x,y)
torch.mul(x,y)
torch.div(x,y)

In [ ]:
x_slice=torch.rand(5,3)
print(x_slice)

In [ ]:
x_slice[:,1] ## slicing like numpy array 

In [ ]:
x_slice.reshape(3,5)

In [ ]:
x_slice.reshape(15,)

In [ ]:
x_slice.view(3,-1)

In [ ]:
import numpy as np

In [ ]:
numpy_array=np.ones([3,2])

In [ ]:
numpytotorch=torch.tensor(numpy_array,dtype=torch.int32)

In [ ]:
np.asarray(numpytotorch)

In [ ]:
numpytotorch.numpy()

In [ ]:
torch.from_numpy(numpy_array)

In [ ]:
## bynoy can only handle cpu not the gpu if you want to convert a 
## tensor(gpu) to numpy then you have to convert/move it to cpu first

tensor1=torch.empty(3,6)

In [ ]:
# how to push tensor1 to gpu
if torch.cuda.is_available():
    device=torch.device("cuda")
    print(device)
    tensorG=tensor1.to(device)
    print(tensorG.device)

In [ ]:
if torch.cuda.is_available():
    device=torch.device('cuda')
    x=torch.ones(2,3,device=device)
    x.to('cpu')

In [ ]:
# to tell pytorch that the declared tensor need to calculate the gradient 
## during the optimization phase i have to mention that requires_grad=True
x=torch.ones(3,2,requires_grad=True)

In [ ]:
torch.tensor([3,3],dtype=torch.float16,device=torch.device('cuda'),requires_grad=True)

In [ ]:
# backpropagation 
# first we need to know chain rule
# dz/dx= dz/dy*dy/dx
# next conceps computational graph
#  linear regression
#  loss=()

 ## 
import torch
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0,requires_grad=True)
y_hat=x*w
loss=(y_hat-y)**2## forward pass 
loss.backward()## do the local gradient and backward pass 
print(w.grad)## update the weight according to the gradient 

In [ ]:
## implementation of neural network in numpy 
import numpy as np
# f=w*x
# x=np.array([1,2,3,4],dtype=np.float16)
# y=np.array([2,4,6,8],dtype=np.float16)
x=np.array([2,2,2,2],dtype=np.float16)
y=np.array([3,3,3,3],dtype=np.float16)
w=0

# MSE=1/N(w*x-y)**2
# dMSE/dw=1/N(w*x)

def forward(x):
    return w*x

def loss(y,y_predicted):
    return ((y-y_predicted)**2).mean()

def gradient(x,y,y_pred):
    
    return np.dot(2*x,(y_pred-y)).mean()

learning_rate=.01
n_iter=30

for epoch in range(n_iter):
    y_prediction = forward(x)
    l= loss(y,y_prediction)
    dw = gradient(x,y,y_prediction)
    w -= learning_rate*dw
    if epoch%2==0:
        print(f'epoch{epoch+1}:w={w:.3f},loss={l:.8f}')

print(f'prediction after training:f(5)={forward(5):.3f}')



In [ ]:
import numpy as np

x=np.array([2,2,3,1],dtype=np.float16)
y=np.array([4,3,2,12],dtype=np.float16)
w=0

n_iter=20
learning_rate=.01

def forward(x):
    # print('----------')
    print(w)
    return x*w
def loss(y,y_pd):
    return ((y_pd-y)**2).mean()
def gradient(x,y,y_pd):
    return np.dot(2*x,(y_pd-y)).mean()

print(f"prediction before training f(5):{forward(5):.3f}")

for epoch in range(n_iter):
    y_pred=forward(x)

    ls=loss(y,y_pred)

    dw=gradient(x,y,y_pred)

    w=w-learning_rate*dw
  
    print(f'epoch{epoch+1}:w={w:.3f},loss={ls:.8f}')

print(f"prediction after training f(5):{forward(5):.3f}")
    



In [ ]:
import torch 

x= torch.tensor([2,2,3,1],dtype=torch.float32)
y=torch.tensor([4,3,2,12],dtype=torch.float32)
w=torch.tensor(0,dtype=torch.float32,requires_grad=True)

def forward(x):
   return(x*w)
def loss(y,ypd):
   return((ypd-y)**2).mean()

print(f"prediction of the modle before training f(6): {forward(5).item():.3f}")

learning_rate=0.01
n_iter=10

for epoch in range(n_iter):
   y_prediction=forward(x)
   l=loss(y,y_prediction)
   ################################ we have to do backpropagartion on loss function ################################################
   l.backward()
   with torch.no_grad():
      w-=learning_rate*w.grad ### negative of w 
   print('----b------')
   print(w)
   w.grad.zero_()
   print('-----a-----')
   print(w)
   if epoch % 20:
      print(f'epoch{epoch+1}:w={w:.3f},loss={l:.5f}')

print(f"prediction of the modle after training f(6): {forward(5).item():.3f}") 

In [ ]:
x=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)

number_sample,number_feature=x.shape
print(f'Number of feature:{number_feature},Number of sample:{number_sample}')
input_size=number_feature
output_size=number_feature

In [ ]:
### Design model(input size, output size, forward pass)
### construct loss and opmtimizer 
### training loop
#### -forward pass:make prediction
#### -backward pass:compute gradient
#### -update weight

import torch
import torch.nn as nn

x=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)

number_sample,number_feature=x.shape
print(f'Number of feature:{number_feature},Number of sample:{number_sample}')
input_size=number_feature
output_size=number_feature

model=nn.Linear(input_size,output_size)
# w=torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# def forward(x):
#    return(x*w)
loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# def loss(y,ypd):
#    return((ypd-y)**2).mean()

print(f"prediction of the modle before training f(6): {forward(5).item():.3f}")

learning_rate=0.01
n_iter=100

for epoch in range(n_iter):
   y_prediction=model(x)

   l= loss(y,y_prediction)
   # l=loss(y,y_prediction)
   l.backward()
   optimizer.step()
   # with torch.no_grad():
   #    w-=learning_rate*w.grad ### negative of w 
   optimizer.zero_grad()
   # w.grad.zero_()

   if epoch % 20:
      w,b=model.parameters()
      print(f'epoch{epoch+1}:w={w[0][0]:.3f},loss={l:.5f}')

print(f"prediction of the modle after training f(6): {forward(5).item():.3f}") 

In [ ]:
### Design model(input size, output size, forward pass)
### construct loss and opmtimizer 
### training loop
#### -forward pass:make prediction
#### -backward pass:compute gradient
#### -update weight

import torch
import torch.nn as nn

x=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)

number_sample,number_feature=x.shape
print(f'Number of feature:{number_feature},Number of sample:{number_sample}')
input_size=number_feature
output_size=number_feature

model=nn.Linear(input_size,output_size)

class Linear_regression(nn.Module):
   def __init__(self,input_dim,output_dim):
      super(Linear_regression,self).__init__()
      self.ln=nn.Linear(input_dim,output_dim)
   def forward(self,x):
      return self.ln(x)

model=Linear_regression(input_size,output_size)
# w=torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# def forward(x):
#    return(x*w)
loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# def loss(y,ypd):
#    return((ypd-y)**2).mean()

print(f"prediction of the modle before training f(6): {forward(5).item():.3f}")

learning_rate=0.01
n_iter=100

for epoch in range(n_iter):
   y_prediction=model(x)

   l= loss(y,y_prediction)
   # l=loss(y,y_prediction)
   l.backward()
   optimizer.step()
   # with torch.no_grad():
   #    w-=learning_rate*w.grad ### negative of w 
   optimizer.zero_grad()
   # w.grad.zero_()

   if epoch % 20:
      w,b=model.parameters()
      print(f'epoch{epoch+1}:w={w[0][0]:.3f},loss={l:.5f}')

print(f"prediction of the model after training f(5): {forward(5).item():.3f}") 

In [ ]:
## try to incorporate all our learn concepts
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
## prepare dataset
x_numpy,y_numpy=datasets.make_regression(n_samples=100,n_features=1,noise=20,random_state=4)
import matplotlib.pyplot as pl

X=torch.from_numpy(x_numpy.astype(np.float32))
y=torch.from_numpy(y_numpy.astype(np.float32))

y = y.view(y.shape[0], 1)


## Define model 
class regression(nn.Module):
   def __init__(self,input_size,output_size):
      super(regression,self).__init__()
      self.ln=nn.Linear(input_size,output_size)

   def forward(self,x):
      return self.ln(x)
sample,feature=X.shape
# print(feature)
input_size=feature
output_size=feature
model=regression(input_size,output_size)
# print(model)
## Train

## Model parameters
learning_rate=0.01
n_iter=500
ls=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# X_pred_b=model(X).detach().numpy()

## train
for epoch in range(n_iter):
   y_pred=model(X)
   # print(y.type)
   loss=ls(y_pred,y)
   # print(type(loss))
   loss.backward()
   optimizer.step()
   optimizer.zero_grad()
   if epoch%100==0:
      w,b=model.parameters()
      print(f"epoch: {epoch+1}, weight: {w[0][0]}, loss: {loss}")
y_pd=model(X).detach().numpy()

pl.plot(x_numpy,y_pd,'r')
pl.scatter(x_numpy,y_numpy)





In [ ]:
import torch
import torch.nn as nn
import numpy as np
import sklearn
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
# 0) Prepare data
X_numpy, y_numpy = datasets.make_classification(n_samples=5000,n_classes=2, random_state=4)
import matplotlib.pyplot as pl
# pl.scatter(X_numpy,y_numpy)
# cast to float Tensor
x_train,  x_test, y_train,y_test =train_test_split(X_numpy, y_numpy)

x_train = torch.from_numpy(x_train.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
x_test = torch.from_numpy(x_test.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))
y_train = y_train.view(y_train.shape[0], 1)
y_test= y_test.view(y_test.shape[0], 1)

n_samples, n_features = x_train.shape

# 1) Model
# Linear model f = wx + b
input_size = n_features
output_class = 1

class Model(nn.Module):
    def __init__(self, input_size,output_class):
        super(Model, self).__init__()
        self.ln=nn.Linear(input_size,output_class)
    def forward(self,x):
        p=torch.sigmoid(self.ln(x))
        return(p)
        
model = Model(input_size, output_class)
# 2) Loss and optimizer
learning_rate = 0.01
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  

# 3) Training loop
num_epochs = 100
def accuracy_P(y,yp):
    with torch.no_grad():
        y_predP=yp.round()
        
        acc=y_predP.eq(y).sum()/float(y.shape[0])

        
    return acc.item()

for epoch in range(num_epochs):
    # Forward pass and loss
    y_predicted = model(x_train)
    # print(y.type)
    loss = criterion(y_predicted, y_train)
    
    with torch.no_grad():
        acc=accuracy_P(y_train,y_predicted)
        # print(acc)

    # print(type(loss))
    
    # Backward pass and update
    loss.backward()
    optimizer.step()

    # zero grad before new step
    optimizer.zero_grad()

    if (epoch+1) % 3 == 0:
        print(f'epoch: {epoch+1}, loss: {loss.item():.4f},accuracy: {acc:.4f}')

# prediction

# with torch.no_grad():
y_pred=model(x_test)
y_predP=y_pred.round()
acc=y_predP.eq(y_test).sum()/float(y_test.shape[0])
print(f'accuracy: {acc.item():.4f}')


In [87]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math
import torch.nn as nn


# gradient computation etc. not efficient for whole data set
# -> divide dataset into small batches

'''
# training loop
for epoch in range(num_epochs):
    # loop over all batches
    for i in range(total_batches):
        batch_x, batch_y = ...
'''

# epoch = one forward and backward pass of ALL training samples
# batch_size = number of training samples used in one forward/backward pass
# number of iterations = number of passes, each pass (forward+backward) using [batch_size] number of sampes
# e.g : 100 samples, batch_size=20 -> 100/20=5 iterations for 1 epoch

# --> DataLoader can do the batch computation for us

# Implement a custom Dataset:
# inherit Dataset
# implement __init__ , __getitem__ , and __len__
"""
first implement to classes for dataset and training
"""
class WineDataset(Dataset):

    def __init__(self):
        # Initialize data, download, etc.
        # read with numpy or pandas
        xy = np.loadtxt('wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.n_samples = xy.shape[0]

        # here the first column is the class label, the rest are the features
        self.x_data = torch.from_numpy(xy[:, 1:]) # size [n_samples, n_features]
        self.y_data = (torch.from_numpy(xy[:,0])).type(torch.LongTensor) # size [n_samples, 1]
        self.y_data=self.y_data-1

    # support indexing such that dataset[i] can be used to get i-th sample
    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]

    # we can call len(dataset) to return the size
    def __len__(self):
        return self.n_samples

class classification_Net(nn.Module):
    def __init__(self,in_dim,hidden_state,out_dim):
        super(classification_Net, self).__init__()
        self.fc1 = nn.Linear(in_dim,hidden_state[0])
        self.relu1 = nn.ReLU()
        self.fc2=nn.Linear(hidden_state[0],hidden_state[1])
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(hidden_state[1],out_dim)

    def forward(self,x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        return x


######################################################################
"""Data set preapraring """
dataset=WineDataset()
features,labels=dataset[0]
dataloader=DataLoader(dataset,batch_size=10,shuffle=True)

"""" Hyperparameters"""
input_dim1=features.shape[0]
output_dim=3
hidden_state=[15,10]
model=classification_Net(in_dim=input_dim1,hidden_state=hidden_state,out_dim=output_dim)
#print(model)

######################################################################  
learning_rate=.01
num_epochs=50
batch_size=10
n_iter=len(dataset)/batch_size

ls=nn.CrossEntropyLoss()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# def acc(y_pred,y_true):

#     return (y_pred.eq(y_true)).sum().item() / y_true.


######################################################################
"""Training"""
def accuracy_P(y,yp):
    with torch.no_grad():
        y_predP=yp.round()
        
        acc=y_predP.eq(y).sum()/float(y.shape[0])

        
    return acc.item()

######################################################################
for epoch in range(num_epochs):
    for i,(inputs,labels) in enumerate(dataloader):
        print((labels))
        y_pred=model(inputs)
        print(y_pred)
        m = nn.Softmax(dim=1)
        _, predicted = torch.max(y_pred.data, 1)
        print(predicted)
        print(m(y_pred))
        _, predicted = torch.max(m(y_pred).data, 1)
        print(predicted)
        
        acc = 100.0 * (((predicted==labels).sum()) /batch_size)
        
        # with torch.no_grad():
        #     acc=accuracy_P(labels,y_predicted)

    
        loss=ls(y_pred,labels)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        # w,b=model.parameters()
        
        print(f'Epoch:{epoch+1},iteration:{i+1},loss:{loss.item()}, accuracy:{acc}')


tensor([1, 2, 0, 1, 0, 1, 1, 0, 1, 2])
tensor([[ -5.2697,  19.8040,  25.9669],
        [ -6.6088,  28.2518,  36.0367],
        [-11.1373,  54.1108,  66.4106],
        [ -5.5181,  23.1083,  29.6842],
        [-14.7462,  74.4751,  90.3382],
        [ -5.3132,  22.5020,  28.8009],
        [ -6.9813,  29.6838,  37.6345],
        [-11.6832,  60.0370,  72.8897],
        [ -6.1832,  20.2912,  27.5177],
        [ -6.5988,  27.5536,  35.3896]], grad_fn=<AddmmBackward0>)
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([[2.7116e-14, 2.1019e-03, 9.9790e-01],
        [3.0139e-19, 4.1580e-04, 9.9958e-01],
        [2.0959e-34, 4.5527e-06, 1.0000e+00],
        [5.1428e-16, 1.3916e-03, 9.9861e-01],
        [0.0000e+00, 1.2905e-07, 1.0000e+00],
        [1.5262e-15, 1.8351e-03, 9.9816e-01],
        [4.2019e-20, 3.5229e-04, 9.9965e-01],
        [1.8642e-37, 2.6193e-06, 1.0000e+00],
        [2.3097e-15, 7.2650e-04, 9.9927e-01],
        [5.8141e-19, 3.9509e-04, 9.9960e-01]], grad_fn=<SoftmaxBackward0>)
tensor

In [69]:
import torchvision
class WineDataset(Dataset):

    def __init__(self,transform=None):
        # Initialize data, download, etc.
        # read with numpy or pandas
        xy = np.loadtxt('wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.n_samples = xy.shape[0]
        # here the first column is the class label, the rest are the features
        self.x_data = xy[:, 1:] # size [n_samples, n_features]
        self.y_data = xy[:,[0]] # size [n_samples, 1]
        

        self.transform = transform
    # support indexing such that dataset[i] can be used to get i-th sample
    def __getitem__(self, index):
        sample=self.x_data[index],self.y_data[index]
        if self.transform:
            sample=self.transform(sample)
        return sample
        # we can call len(dataset) to return the size
    def __len__(self):
        return self.n_samples

class To_tensor:
    def __call__(self,sample):
        feature,labels = sample
        return torch.from_numpy(feature), torch.from_numpy(labels)
class Factor:
    def __init__(self,factor):
        self.factor = factor
    def __call__(self,sample):
        feature,labels = sample
        return feature * self.factor, labels


composed=torchvision.transforms.Compose([To_tensor(),Factor(0.5)])

dataset = WineDataset(transform=composed)
first_data = dataset[0]
features, labels = first_data
print(features,labels)



tensor([7.1150e+00, 8.5500e-01, 1.2150e+00, 7.8000e+00, 6.3500e+01, 1.4000e+00,
        1.5300e+00, 1.4000e-01, 1.1450e+00, 2.8200e+00, 5.2000e-01, 1.9600e+00,
        5.3250e+02]) tensor([1.])


In [82]:
## important ##
a = torch.randn(4, 3)
print(a)
x,y=torch.max(a, 1)
print(x)##it gives us max vakue
print(y)## it gives us index


tensor([[ 1.2680, -0.6568, -0.1023],
        [ 0.8658,  0.1297, -0.1932],
        [-0.4327,  0.6664, -0.5403],
        [-2.2400,  0.3915, -0.0378]])
tensor([1.2680, 0.8658, 0.6664, 0.3915])
tensor([0, 0, 1, 1])
