In [6]:
import torch 
x=torch.empty(3,2)
print(x)
x.shape

tensor([[-2.7725e-21,  4.5895e-41],
        [-7.7053e-35,  3.0644e-41],
        [ 0.0000e+00,  0.0000e+00]])


torch.Size([3, 2])

In [9]:
x_rand=torch.rand(2,3)
print(x_rand)
print(x_rand.dtype)

tensor([[0.5163, 0.6662, 0.3572],
        [0.9209, 0.9972, 0.0017]])
torch.float32


In [11]:
x_dt=torch.ones(2,2,dtype=torch.float16)
print(x_dt.dtype)

torch.float16


In [12]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x+y)

tensor([[0.7399, 1.7881],
        [0.7786, 1.3155]])


In [14]:
y.add_(x)## _ means in place operation

tensor([[1.3756, 2.6697],
        [1.4816, 1.8891]])

In [16]:
torch.subtract(x,y)
torch.mul(x,y)
torch.div(x,y)

tensor([[0.4621, 0.3302],
        [0.4745, 0.3036]])

In [17]:
x_slice=torch.rand(5,3)
print(x_slice)

tensor([[0.6952, 0.6693, 0.4393],
        [0.3997, 0.0474, 0.9590],
        [0.0713, 0.1092, 0.1300],
        [0.0143, 0.2588, 0.5623],
        [0.4019, 0.8602, 0.2614]])


In [18]:
x_slice[:,1] ## slicing like numpy array 

tensor([0.6693, 0.0474, 0.1092, 0.2588, 0.8602])

In [20]:
x_slice.reshape(3,5)

tensor([[0.6952, 0.6693, 0.4393, 0.3997, 0.0474],
        [0.9590, 0.0713, 0.1092, 0.1300, 0.0143],
        [0.2588, 0.5623, 0.4019, 0.8602, 0.2614]])

In [21]:
x_slice.reshape(15,)

tensor([0.6952, 0.6693, 0.4393, 0.3997, 0.0474, 0.9590, 0.0713, 0.1092, 0.1300,
        0.0143, 0.2588, 0.5623, 0.4019, 0.8602, 0.2614])

In [22]:
x_slice.view(3,-1)

tensor([[0.6952, 0.6693, 0.4393, 0.3997, 0.0474],
        [0.9590, 0.0713, 0.1092, 0.1300, 0.0143],
        [0.2588, 0.5623, 0.4019, 0.8602, 0.2614]])

In [23]:
import numpy as np

In [26]:
numpy_array=np.ones([3,2])

In [30]:
numpytotorch=torch.tensor(numpy_array,dtype=torch.int32)

In [31]:
np.asarray(numpytotorch)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [32]:
numpytotorch.numpy()

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [34]:
torch.from_numpy(numpy_array)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [35]:
## bynoy can only handle cpu not the gpu if you want to convert a 
## tensor(gpu) to numpy then you have to convert/move it to cpu first

tensor1=torch.empty(3,6)

In [43]:
# how to push tensor1 to gpu
if torch.cuda.is_available():
    device=torch.device("cuda")
    print(device)
    tensorG=tensor1.to(device)
    print(tensorG.device)

cuda
cuda:0


In [40]:
if torch.cuda.is_available():
    device=torch.device('cuda')
    x=torch.ones(2,3,device=device)
    x.to('cpu')

In [41]:
# to tell pytorch that the declared tensor need to calculate the gradient 
## during the optimization phase i have to mention that requires_grad=True
x=torch.ones(3,2,requires_grad=True)

In [46]:
torch.tensor([3,3],dtype=torch.float16,device=torch.device('cuda'),requires_grad=True)

tensor([3., 3.], device='cuda:0', dtype=torch.float16, requires_grad=True)

In [47]:
# backpropagation 
# first we need to know chain rule
# dz/dx= dz/dy*dy/dx
# next conceps computational graph
#  linear regression
#  loss=()

 ## 
import torch
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0,requires_grad=True)
y_hat=x*w
loss=(y_hat-y)**2## forward pass 
loss.backward()## do the local gradient and backward pass 
print(w.grad)## update the weight according to the gradient 

tensor(-2.)


In [55]:
## implementation of neural network in numpy 
import numpy as np
# f=w*x
x=np.array([1,2,3,4],dtype=np.float16)
y=np.array([2,4,6,8],dtype=np.float16)
w=0

# MSE=1/N(w*x-y)**2
# dMSE/dw=1/N(w*x)

def forward(x):
    return w*x

def loss(y,y_predicted):
    return ((y-y_predicted)**2).mean()

def gradient(x,y,y_pred):
    return np.dot(2*x,(y_pred-y)).mean()

learning_rate=.01
n_iter=30

for epoch in range(n_iter):
    y_prediction = forward(x)
    l= loss(y,y_prediction)
    dw = gradient(x,y,y_prediction)
    w -= learning_rate*dw
    if epoch%2==0:
        print(f'epoch{epoch+1}:w={w:.3f},loss={l:.8f}')

print(f'prediction after training:f(5)={forward(5):.3f}')



epoch1:w=1.200,loss=30.00000000
epoch3:w=1.872,loss=0.76953125
epoch5:w=1.980,loss=0.02015686
epoch7:w=1.997,loss=0.00045776
epoch9:w=2.000,loss=0.00003529
epoch11:w=2.000,loss=0.00000000
epoch13:w=2.000,loss=0.00000000
epoch15:w=2.000,loss=0.00000000
epoch17:w=2.000,loss=0.00000000
epoch19:w=2.000,loss=0.00000000
epoch21:w=2.000,loss=0.00000000
epoch23:w=2.000,loss=0.00000000
epoch25:w=2.000,loss=0.00000000
epoch27:w=2.000,loss=0.00000000
epoch29:w=2.000,loss=0.00000000
prediction after training:f(5)=9.999


In [53]:
import numpy as np 

# Compute every step manually

# Linear regression
# f = w * x 

# here : f = 2 * x
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

# J = MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N * 2x(w*x - y)
def gradient(x, y, y_pred):
    return np.dot(2*x, y_pred - y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients
    dw = gradient(X, Y, y_pred)

    # update weights
    w -= learning_rate * dw

    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 3: w = 1.872, loss = 0.76800019
epoch 5: w = 1.980, loss = 0.01966083
epoch 7: w = 1.997, loss = 0.00050331
epoch 9: w = 1.999, loss = 0.00001288
epoch 11: w = 2.000, loss = 0.00000033
epoch 13: w = 2.000, loss = 0.00000001
epoch 15: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000
