In [6]:
import torch 
x=torch.empty(3,2)
print(x)
x.shape

tensor([[-2.7725e-21,  4.5895e-41],
        [-7.7053e-35,  3.0644e-41],
        [ 0.0000e+00,  0.0000e+00]])


torch.Size([3, 2])

In [9]:
x_rand=torch.rand(2,3)
print(x_rand)
print(x_rand.dtype)

tensor([[0.5163, 0.6662, 0.3572],
        [0.9209, 0.9972, 0.0017]])
torch.float32


In [11]:
x_dt=torch.ones(2,2,dtype=torch.float16)
print(x_dt.dtype)

torch.float16


In [12]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x+y)

tensor([[0.7399, 1.7881],
        [0.7786, 1.3155]])


In [14]:
y.add_(x)## _ means in place operation

tensor([[1.3756, 2.6697],
        [1.4816, 1.8891]])

In [16]:
torch.subtract(x,y)
torch.mul(x,y)
torch.div(x,y)

tensor([[0.4621, 0.3302],
        [0.4745, 0.3036]])

In [17]:
x_slice=torch.rand(5,3)
print(x_slice)

tensor([[0.6952, 0.6693, 0.4393],
        [0.3997, 0.0474, 0.9590],
        [0.0713, 0.1092, 0.1300],
        [0.0143, 0.2588, 0.5623],
        [0.4019, 0.8602, 0.2614]])


In [18]:
x_slice[:,1] ## slicing like numpy array 

tensor([0.6693, 0.0474, 0.1092, 0.2588, 0.8602])

In [20]:
x_slice.reshape(3,5)

tensor([[0.6952, 0.6693, 0.4393, 0.3997, 0.0474],
        [0.9590, 0.0713, 0.1092, 0.1300, 0.0143],
        [0.2588, 0.5623, 0.4019, 0.8602, 0.2614]])

In [21]:
x_slice.reshape(15,)

tensor([0.6952, 0.6693, 0.4393, 0.3997, 0.0474, 0.9590, 0.0713, 0.1092, 0.1300,
        0.0143, 0.2588, 0.5623, 0.4019, 0.8602, 0.2614])

In [22]:
x_slice.view(3,-1)

tensor([[0.6952, 0.6693, 0.4393, 0.3997, 0.0474],
        [0.9590, 0.0713, 0.1092, 0.1300, 0.0143],
        [0.2588, 0.5623, 0.4019, 0.8602, 0.2614]])

In [23]:
import numpy as np

In [26]:
numpy_array=np.ones([3,2])

In [30]:
numpytotorch=torch.tensor(numpy_array,dtype=torch.int32)

In [31]:
np.asarray(numpytotorch)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [32]:
numpytotorch.numpy()

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [34]:
torch.from_numpy(numpy_array)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [35]:
## bynoy can only handle cpu not the gpu if you want to convert a 
## tensor(gpu) to numpy then you have to convert/move it to cpu first

tensor1=torch.empty(3,6)

In [43]:
# how to push tensor1 to gpu
if torch.cuda.is_available():
    device=torch.device("cuda")
    print(device)
    tensorG=tensor1.to(device)
    print(tensorG.device)

cuda
cuda:0


In [40]:
if torch.cuda.is_available():
    device=torch.device('cuda')
    x=torch.ones(2,3,device=device)
    x.to('cpu')

In [41]:
# to tell pytorch that the declared tensor need to calculate the gradient 
## during the optimization phase i have to mention that requires_grad=True
x=torch.ones(3,2,requires_grad=True)

In [46]:
torch.tensor([3,3],dtype=torch.float16,device=torch.device('cuda'),requires_grad=True)

tensor([3., 3.], device='cuda:0', dtype=torch.float16, requires_grad=True)

In [47]:
# backpropagation 
# first we need to know chain rule
# dz/dx= dz/dy*dy/dx
# next conceps computational graph
#  linear regression
#  loss=()

 ## 
import torch
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0,requires_grad=True)
y_hat=x*w
loss=(y_hat-y)**2## forward pass 
loss.backward()## do the local gradient and backward pass 
print(w.grad)## update the weight according to the gradient 

tensor(-2.)


In [34]:
## implementation of neural network in numpy 
import numpy as np
# f=w*x
# x=np.array([1,2,3,4],dtype=np.float16)
# y=np.array([2,4,6,8],dtype=np.float16)
x=np.array([2,2,2,2],dtype=np.float16)
y=np.array([3,3,3,3],dtype=np.float16)
w=0

# MSE=1/N(w*x-y)**2
# dMSE/dw=1/N(w*x)

def forward(x):
    return w*x

def loss(y,y_predicted):
    return ((y-y_predicted)**2).mean()

def gradient(x,y,y_pred):
    
    return np.dot(2*x,(y_pred-y)).mean()

learning_rate=.01
n_iter=30

for epoch in range(n_iter):
    y_prediction = forward(x)
    l= loss(y,y_prediction)
    dw = gradient(x,y,y_prediction)
    w -= learning_rate*dw
    if epoch%2==0:
        print(f'epoch{epoch+1}:w={w:.3f},loss={l:.8f}')

print(f'prediction after training:f(5)={forward(5):.3f}')



epoch1:w=0.480,loss=9.00000000
epoch3:w=1.028,loss=1.92578125
epoch5:w=1.282,loss=0.41040039
epoch7:w=1.399,loss=0.08813477
epoch9:w=1.453,loss=0.01869202
epoch11:w=1.478,loss=0.00390625
epoch13:w=1.490,loss=0.00085831
epoch15:w=1.495,loss=0.00018692
epoch17:w=1.498,loss=0.00003433
epoch19:w=1.499,loss=0.00001526
epoch21:w=1.500,loss=0.00000381
epoch23:w=1.500,loss=0.00000000
epoch25:w=1.500,loss=0.00000000
epoch27:w=1.500,loss=0.00000000
epoch29:w=1.500,loss=0.00000000
prediction after training:f(5)=7.498


In [50]:
import numpy as np

x=np.array([2,2,3,1],dtype=np.float16)
y=np.array([4,3,2,12],dtype=np.float16)
w=0

n_iter=20
learning_rate=.01

def forward(x):
    # print('----------')
    print(w)
    return x*w
def loss(y,y_pd):
    return ((y_pd-y)**2).mean()
def gradient(x,y,y_pd):
    return np.dot(2*x,(y_pd-y)).mean()

print(f"prediction before training f(5):{forward(5):.3f}")

for epoch in range(n_iter):
    y_pred=forward(x)

    ls=loss(y,y_pred)

    dw=gradient(x,y,y_pred)

    w=w-learning_rate*dw
  
    print(f'epoch{epoch+1}:w={w:.3f},loss={ls:.8f}')

print(f"prediction after training f(5):{forward(5):.3f}")
    



0
prediction before training f(5):0.000
0
epoch1:w=0.640,loss=43.25000000
0.64
epoch2:w=1.049,loss=34.84375000
1.049375
epoch3:w=1.312,loss=31.43750000
1.3115625
epoch4:w=1.479,loss=30.00000000
1.4793749999999999
epoch5:w=1.587,loss=29.43750000
1.5868749999999998
epoch6:w=1.656,loss=29.18750000
1.6555468749999998
epoch7:w=1.700,loss=29.09375000
1.6996874999999998
epoch8:w=1.728,loss=29.03125000
1.727890625
epoch9:w=1.746,loss=29.04687500
1.7459375
epoch10:w=1.757,loss=29.01562500
1.7572656249999998
epoch11:w=1.765,loss=29.01562500
1.7648437499999998
epoch12:w=1.770,loss=29.03125000
1.769609375
epoch13:w=1.773,loss=29.04687500
1.7726562499999998
epoch14:w=1.775,loss=29.01562500
1.7746093749999998
epoch15:w=1.776,loss=29.03125000
1.7757812499999999
epoch16:w=1.777,loss=29.03125000
1.7765624999999998
epoch17:w=1.777,loss=29.03125000
1.7771875
epoch18:w=1.777,loss=29.01562500
1.7772656249999998
epoch19:w=1.777,loss=29.01562500
1.7773437499999998
epoch20:w=1.777,loss=29.01562500
1.777421874

In [58]:
import torch 

x= torch.tensor([2,2,3,1],dtype=torch.float32)
y=torch.tensor([4,3,2,12],dtype=torch.float32)
w=torch.tensor(0,dtype=torch.float32,requires_grad=True)

def forward(x):
   return(x*w)
def loss(y,ypd):
   return((ypd-y)**2).mean()

print(f"prediction of the modle before training f(6): {forward(5).item():.3f}")

learning_rate=0.01
n_iter=10000

for epoch in range(n_iter):
   y_prediction=forward(x)
   l=loss(y,y_prediction)
   ################################ we have to do backpropagartion on loss function ################################################
   l.backward()
   with torch.no_grad():
      w-=learning_rate*w.grad ### negative of w 
   
   w.grad.zero_()
   
   if epoch % 20:
      print(f'epoch{epoch+1}:w={w:.3f},loss={l:.5f}')

print(f"prediction of the modle after training f(6): {forward(5).item():.3f}") 

prediction of the modle before training f(6): 0.000
epoch2:w=0.306,loss=40.80520
epoch3:w=0.438,loss=38.78066
epoch4:w=0.559,loss=37.10414
epoch5:w=0.668,loss=35.71582
epoch6:w=0.768,loss=34.56614
epoch7:w=0.859,loss=33.61410
epoch8:w=0.942,loss=32.82571
epoch9:w=1.017,loss=32.17284
epoch10:w=1.085,loss=31.63221
epoch11:w=1.148,loss=31.18451
epoch12:w=1.204,loss=30.81376
epoch13:w=1.256,loss=30.50675
epoch14:w=1.303,loss=30.25252
epoch15:w=1.346,loss=30.04198
epoch16:w=1.385,loss=29.86764
epoch17:w=1.420,loss=29.72327
epoch18:w=1.452,loss=29.60371
epoch19:w=1.482,loss=29.50471
epoch20:w=1.508,loss=29.42273
epoch22:w=1.555,loss=29.29862
epoch23:w=1.575,loss=29.25206
epoch24:w=1.593,loss=29.21350
epoch25:w=1.610,loss=29.18158
epoch26:w=1.625,loss=29.15514
epoch27:w=1.638,loss=29.13325
epoch28:w=1.651,loss=29.11511
epoch29:w=1.662,loss=29.10010
epoch30:w=1.673,loss=29.08767
epoch31:w=1.682,loss=29.07738
epoch32:w=1.691,loss=29.06885
epoch33:w=1.699,loss=29.06179
epoch34:w=1.706,loss=29.05

tensor(0., requires_grad=True)